# Generated by Django 4.1 on 2022-12-09 12:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=50, verbose_name="Meslek")),
                ("sector", models.CharField(max_length=50, verbose_name="Sektör")),
                ("content", ckeditor.fields.RichTextField(verbose_name="Ön Yazı")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "personal_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Fotoğraf Ekleyiniz",
                    ),
                ),
                (
                    "personal_cv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Lütfen CV'nizi ekleyiniz",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aday",
                    ),
                ),
            ],
            options={"ordering": ["-created_date"],},
        ),
    ]
