# Generated by Django 4.1 on 2022-12-22 08:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="content",
            field=ckeditor.fields.RichTextField(
                max_length=200, verbose_name="Ön Yazı (Max 200 karakter Giriniz)"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="position",
            field=models.CharField(
                choices=[
                    ("Software Engineer", "Software Engineer"),
                    ("Akademisyen", "Akademisyen"),
                    ("Tıp Hekimi", "Tıp Hekimi"),
                    ("Diş Hekimi", "Diş Hekimi"),
                    ("Elektrik&Elektronik Mühendisi", "Elektrik&Elektronik Mühendisi"),
                    ("İnşaat Mühdendisi", "İnşaat Mühdendisi"),
                    ("Mimar", "Mimar"),
                    ("Muhasebeci", "Muhasebeci"),
                    ("Program Manager", "Program Manager"),
                    ("Ürün Yönetimi Uzmanı", "Ürün Yönetimi Uzmanı"),
                    (
                        "Elektronik ve Haberleşme Mühendisi",
                        "Elektronik ve Haberleşme Mühendisi",
                    ),
                    ("E-Ticaret Uzmanı", "E-Ticaret Uzmanı"),
                    ("Öğretmen", "Öğretmen"),
                    ("Borsa/Finans Uzmanı", "Borsa/Finans Uzmanı"),
                    ("Endüstri Mühendisi", "Endüstri Mühendisi"),
                    ("İnsan Kaynakları ", "İnsan Kaynakları"),
                    ("Avukat", "Avukat"),
                    ("Satış ve Pazarlama Uzmanı", "Satış ve Pazarlama Uzmanı"),
                    ("Network Security Engineer", "Network Security Engineer"),
                    ("IT Sistem Yöneticisi", "IT Sistem Yöneticisi"),
                    ("Diğer", "Diğer"),
                ],
                max_length=50,
                verbose_name="Departman",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="sector",
            field=models.CharField(
                choices=[
                    ("Ar-Ge", "Ar-Ge"),
                    ("Bilişim", "Bilişim"),
                    ("Bilgi Teknolojileri", "Bilgi Teknolojileri"),
                    ("Üretim / Endüstriyel Ürünler", "Üretim / Endüstriyel Ürünler"),
                    ("Elektrik & Elektronik", "Elektrik & Elektronik"),
                    ("Güvenlik", "Güvenlik"),
                    ("Enerji", "Enerji"),
                    ("Gıda", "Gıda"),
                    ("Kimya", "Kimya"),
                    ("Maden ve Metal Sanayi", "Maden ve Metal Sanayi"),
                    ("Mobilya & Aksesuar", "Mobilya & Aksesuar"),
                    ("Ev Eşyaları", "Ev Eşyaları"),
                    ("Orman Ürünleri", "Orman Ürünleri"),
                    ("Ofis / Büro Malzemeleri", "Ofis / Büro Malzemeleri"),
                    ("Otomotiv", "Otomotiv"),
                    ("Sağlık", "Sağlık"),
                    ("Tarım / Ziraat", "Tarım / Ziraat"),
                    ("Taşımacılık", "Taşımacılık"),
                    ("Tekstil", "Tekstil"),
                    ("Telekomünikasyon", "Telekomünikasyon"),
                    ("Turizm", "Turizm"),
                    ("Yapı", "Yapı"),
                    ("Topluluklar", "Topluluklar"),
                    ("Hizmet", "Hizmet"),
                    ("Danışmanlık", "Danışmanlık"),
                    ("Reklam ve Tanıtım", "Reklam ve Tanıtım"),
                    ("Eğitim", "Eğitim"),
                    ("Finans - Ekonomi", "Finans - Ekonomi"),
                    ("Ticaret", "Ticaret"),
                    ("Denizcilik", "Denizcilik"),
                    ("Eğlence - Kültür - Sanat", "Eğlence - Kültür - Sanat"),
                    ("Basım - Yayın", "Basım - Yayın"),
                    ("Medya", "Medya"),
                    ("Havacılık", "Havacılık"),
                    ("Hızlı Tüketim Malları", "Hızlı Tüketim Malları"),
                    ("Sigortacılık", "Sigortacılık"),
                    ("Perakende", "Perakende"),
                    ("İletişim Danışmanlığı", "İletişim Danışmanlığı"),
                    ("Bilgi Teknolojileri", "Bilgi Teknolojileri"),
                    ("Dental", "Dental"),
                    ("Organizasyon", "Organizasyon"),
                    ("Diğer", "Diğer"),
                ],
                max_length=60,
                verbose_name="Sektör",
            ),
        ),
    ]
