# Generated by Django 4.1 on 2022-12-07 13:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="address", field=ckeditor.fields.RichTextField(),
        ),
    ]
